comsave_salesforce_outbound_message:
    wsdl_directory: 'wsdl/directory'
    document_paths:
        Product2:
            path: 'path/to/document'
        DiscountRule__c:
            path: 'path/to/otherdocument'