language: php

php:
  #  - 7.2
  - 7.3
#  - 7.4

before_install: >
  cat /etc/issue;
  apt-get install jq;
  for symfony_dependency in $(cat composer.json | jq '.require | to_entries[] | .key' | egrep -o "symfony/[^\"]+"); do composer require "symfony/config:${SYMFONY_VERSION}" --no-update; done

install: composer install --no-interaction

script:
  - bin/console cache:clear --env=prod
  - composer run-coverage

env:
  global:
    - CC_TEST_REPORTER_ID=ade3e812370d0201d8abc6f28208859b755b9cd188d2f9139cfbdcb3fc309dcf
    - SYMFONY_VERSION=^5.0

matrix:
  include:
    - php: 7.3
      env: SYMFONY_VERSION=^3.4
    - php: 7.3
      env: SYMFONY_VERSION=^4.3
    - php: 7.3
      env: SYMFONY_VERSION=^5.0

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - mv Tests/_output/coverage.xml clover.xml
  - ./cc-test-reporter after-build --coverage-input-type clover --id $CC_TEST_REPORTER_ID --exit-code $TRAVIS_TEST_RESULT
