services:
    Comsave\SalesforceOutboundMessageBundle\:
            autowire: true
            autoconfigure: true
            public: true
            resource: '../../*'

    Comsave\SalesforceOutboundMessageBundle\Services\Factory\OutboundMessageWsdlPathFactory:
            arguments:
                - '%comsave_salesforce_outbound_message.wsdl_directory%'

    Comsave\SalesforceOutboundMessageBundle\Services\Factory\OutboundMessageDocumentClassNameFactory:
            arguments:
                - '%comsave_salesforce_outbound_message.document_paths%'
