services:
#    comsave_salesforce_outbound_message.example:
#        class: Comsave\SalesforceOutboundMessageBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    Comsave\SalesforceOutboundMessageBundle\Services\ConfigReader:
        public: true
        arguments: ['%comsave_salesforce_outbound_message.wsdl_directory%']