services:
    SalesforceOutboundMessageBundle\:
        autowire: true
        autoconfigure: true
        public: false
        resource: '../../*'
        exclude: '../../{Document,Repository}'

    SalesforceOutboundMessageBundle\Controller\:
        autowire: true
        autoconfigure: true
        public: true
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    SalesforceOutboundMessageBundle\Services\Factory\OutboundMessageWsdlPathFactory:
        public: true
        arguments: ['%salesforce_wsdl_directory%']

    SalesforceOutboundMessageBundle\Services\Factory\OutboundMessageDocumentClassNameFactory:
        public: true
        arguments: ['%salesforce_documents%']
